filter:
    excluded_paths:
        - 'bin/*'
        - 'page/jquery*'
        - 'include/PHP-cast-to-type/*'
checks:
    php:
        fix_php_opening_tag: false
        remove_php_closing_tag: false
        one_class_per_file: false
        side_effects_or_types: false
        no_mixed_inline_html: false
        require_braces_around_control_structures: false
        php5_style_constructor: false
        no_global_keyword: true
        avoid_usage_of_logical_operators: true
        psr2_class_declaration: false
        no_underscore_prefix_in_properties: true
        no_underscore_prefix_in_methods: true
        blank_line_after_namespace_declaration: false
        single_namespace_per_use: false
        psr2_switch_declaration: false
        psr2_control_structure_declaration: false
        avoid_superglobals: false
        security_vulnerabilities: true
        no_exit: false
        use_self_instead_of_fqcn: true
        uppercase_constants: true
        simplify_boolean_return: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        prefer_while_loop_over_for_loop: true
        parameter_doc_comments: true
        param_doc_comment_if_not_inferrable: true
        optional_parameters_at_the_end: true
        no_short_variable_names:
            minimum: '3'
        no_short_method_names:
            minimum: '5'
        no_long_variable_names:
            maximum: '25'
        no_goto: true
        newline_at_end_of_file: true
        more_specific_types_in_doc_comments: true
        encourage_single_quotes: true
        encourage_postdec_operator: true
        coding_standard:
            name: WordPress
        avoid_unnecessary_concatenation: true
        avoid_perl_style_comments: true
        avoid_multiple_statements_on_same_line: true
        align_assignments: true
        code_rating: true
    javascript:
        wrap_regex: true
        valid_typeof: true
        use_isnan: true
        radix: true
        one_var: true
        no_with: true
        no_void: true
        no_var: true
        no_use_before_define: true
        no_unused_vars: true
        no_unused_expressions: true
        no_unreachable: true
        no_underscore_dangle: true
        no_undefined: true
        no_undef_init: true
        no_undef: true
        no_trailing_spaces: true
        no_sync: true
        no_sparse_arrays: true
        no_shadow: true
        no_self_compare: true
        no_return_assign: true
        no_reserved_keys: true
        no_redeclare: true
        no_process_exit: true
        no_plusplus: true
        no_path_concat: true
        no_octal_escape: true
        no_octal: true
        no_new_require: true
        no_new_object: true
        no_new_wrappers: true
        no_obj_calls: true
        no_new_func: true
        no_new: true
        no_nested_ternary: true
        no_negated_in_lhs: true
        no_native_reassign: true
        no_multi_str: true
        no_mixed_spaces_and_tabs: true
        no_loop_func: true
        no_lonely_if: true
        no_lone_blocks: true
        no_labels: true
        no_label_var: true
        no_iterator: true
        no_irregular_whitespace: true
        no_invalid_regexp: true
        no_inner_declarations: true
        no_func_assign: true
        no_implied_eval: true
        no_floating_decimal: true
        no_fallthrough: true
        no_extra_strict: true
        no_extra_boolean_cast: true
        no_extra_bind: true
        no_eval: true
        no_ex_assign: true
        no_extend_native: true
        no_eq_null: true
        no_empty_label: true
        no_empty_class: true
        no_empty: true
        no_else_return: true
        no_dupe_keys: true
        no_div_regex: true
        no_delete_var: true
        no_debugger: true
        no_control_regex: true
        no_constant_condition: true
        no_console: true
        no_comma_dangle: true
        no_catch_shadow: true
        no_caller: true
        no_bitwise: true
        no_array_constructor: true
        no_alert: true
        new_parens: true
        guard_for_in: true
        eqeqeq: true
        eol_last: true
        dot_notation: true
        default_case: true
        curly: true
        consistent_return: true
        camelcase: true
        block_scoped_var: true

coding_style:
    php:
        indentation:
            general:
                use_tabs: true
        spaces:
            around_operators:
                concatenation: true
                negation: true
            within:
                array_initializer: true
                grouping: true
                function_call: true
                function_declaration: true
                if: true
                for: true
                while: true
                switch: true
                catch: true
            ternary_operator:
                in_short_version: true
        braces:
            classes_functions:
                class: end-of-line
                function: end-of-line
                closure: end-of-line
            if:
                opening: end-of-line
                else_on_new_line: true
            for:
                opening: end-of-line
            while:
                opening: end-of-line
            do_while:
                opening: end-of-line
                while_on_new_line: true
            switch:
                opening: end-of-line
            try:
                opening: end-of-line
                catch_on_new_line: true
                finally_on_new_line: true
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: lower

tools:
    sensiolabs_security_checker: true
